version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
    groups:
      all-dependencies-with-semver:
        patterns:
          - "*"
    versioning-strategy: "increase"
